# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ryan/PSAS/oresat-linux/CANdaemon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ryan/PSAS/oresat-linux/CANdaemon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/PSAS/oresat-linux/CANdaemon/CMakeFiles /home/ryan/PSAS/oresat-linux/CANdaemon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/PSAS/oresat-linux/CANdaemon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named candaemon

# Build rule for target.
candaemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 candaemon
.PHONY : candaemon

# fast build rule for target.
candaemon/fast:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/build
.PHONY : candaemon/fast

#=============================================================================
# Target rules for targets named board

# Build rule for target.
board: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 board
.PHONY : board

# fast build rule for target.
board/fast:
	$(MAKE) -f boards/startracker/CMakeFiles/board.dir/build.make boards/startracker/CMakeFiles/board.dir/build
.PHONY : board/fast

#=============================================================================
# Target rules for targets named OD

# Build rule for target.
OD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OD
.PHONY : OD

# fast build rule for target.
OD/fast:
	$(MAKE) -f boards/startracker/objDict/CMakeFiles/OD.dir/build.make boards/startracker/objDict/CMakeFiles/OD.dir/build
.PHONY : OD/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f common/CMakeFiles/common.dir/build.make common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named driver

# Build rule for target.
driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 driver
.PHONY : driver

# fast build rule for target.
driver/fast:
	$(MAKE) -f common/socketCAN/CMakeFiles/driver.dir/build.make common/socketCAN/CMakeFiles/driver.dir/build
.PHONY : driver/fast

CANopenNode/CANopen.o: CANopenNode/CANopen.c.o

.PHONY : CANopenNode/CANopen.o

# target to build an object file
CANopenNode/CANopen.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/CANopen.c.o
.PHONY : CANopenNode/CANopen.c.o

CANopenNode/CANopen.i: CANopenNode/CANopen.c.i

.PHONY : CANopenNode/CANopen.i

# target to preprocess a source file
CANopenNode/CANopen.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/CANopen.c.i
.PHONY : CANopenNode/CANopen.c.i

CANopenNode/CANopen.s: CANopenNode/CANopen.c.s

.PHONY : CANopenNode/CANopen.s

# target to generate assembly for a file
CANopenNode/CANopen.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/CANopen.c.s
.PHONY : CANopenNode/CANopen.c.s

CANopenNode/stack/CO_Emergency.o: CANopenNode/stack/CO_Emergency.c.o

.PHONY : CANopenNode/stack/CO_Emergency.o

# target to build an object file
CANopenNode/stack/CO_Emergency.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_Emergency.c.o
.PHONY : CANopenNode/stack/CO_Emergency.c.o

CANopenNode/stack/CO_Emergency.i: CANopenNode/stack/CO_Emergency.c.i

.PHONY : CANopenNode/stack/CO_Emergency.i

# target to preprocess a source file
CANopenNode/stack/CO_Emergency.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_Emergency.c.i
.PHONY : CANopenNode/stack/CO_Emergency.c.i

CANopenNode/stack/CO_Emergency.s: CANopenNode/stack/CO_Emergency.c.s

.PHONY : CANopenNode/stack/CO_Emergency.s

# target to generate assembly for a file
CANopenNode/stack/CO_Emergency.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_Emergency.c.s
.PHONY : CANopenNode/stack/CO_Emergency.c.s

CANopenNode/stack/CO_HBconsumer.o: CANopenNode/stack/CO_HBconsumer.c.o

.PHONY : CANopenNode/stack/CO_HBconsumer.o

# target to build an object file
CANopenNode/stack/CO_HBconsumer.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_HBconsumer.c.o
.PHONY : CANopenNode/stack/CO_HBconsumer.c.o

CANopenNode/stack/CO_HBconsumer.i: CANopenNode/stack/CO_HBconsumer.c.i

.PHONY : CANopenNode/stack/CO_HBconsumer.i

# target to preprocess a source file
CANopenNode/stack/CO_HBconsumer.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_HBconsumer.c.i
.PHONY : CANopenNode/stack/CO_HBconsumer.c.i

CANopenNode/stack/CO_HBconsumer.s: CANopenNode/stack/CO_HBconsumer.c.s

.PHONY : CANopenNode/stack/CO_HBconsumer.s

# target to generate assembly for a file
CANopenNode/stack/CO_HBconsumer.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_HBconsumer.c.s
.PHONY : CANopenNode/stack/CO_HBconsumer.c.s

CANopenNode/stack/CO_NMT_Heartbeat.o: CANopenNode/stack/CO_NMT_Heartbeat.c.o

.PHONY : CANopenNode/stack/CO_NMT_Heartbeat.o

# target to build an object file
CANopenNode/stack/CO_NMT_Heartbeat.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_NMT_Heartbeat.c.o
.PHONY : CANopenNode/stack/CO_NMT_Heartbeat.c.o

CANopenNode/stack/CO_NMT_Heartbeat.i: CANopenNode/stack/CO_NMT_Heartbeat.c.i

.PHONY : CANopenNode/stack/CO_NMT_Heartbeat.i

# target to preprocess a source file
CANopenNode/stack/CO_NMT_Heartbeat.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_NMT_Heartbeat.c.i
.PHONY : CANopenNode/stack/CO_NMT_Heartbeat.c.i

CANopenNode/stack/CO_NMT_Heartbeat.s: CANopenNode/stack/CO_NMT_Heartbeat.c.s

.PHONY : CANopenNode/stack/CO_NMT_Heartbeat.s

# target to generate assembly for a file
CANopenNode/stack/CO_NMT_Heartbeat.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_NMT_Heartbeat.c.s
.PHONY : CANopenNode/stack/CO_NMT_Heartbeat.c.s

CANopenNode/stack/CO_PDO.o: CANopenNode/stack/CO_PDO.c.o

.PHONY : CANopenNode/stack/CO_PDO.o

# target to build an object file
CANopenNode/stack/CO_PDO.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_PDO.c.o
.PHONY : CANopenNode/stack/CO_PDO.c.o

CANopenNode/stack/CO_PDO.i: CANopenNode/stack/CO_PDO.c.i

.PHONY : CANopenNode/stack/CO_PDO.i

# target to preprocess a source file
CANopenNode/stack/CO_PDO.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_PDO.c.i
.PHONY : CANopenNode/stack/CO_PDO.c.i

CANopenNode/stack/CO_PDO.s: CANopenNode/stack/CO_PDO.c.s

.PHONY : CANopenNode/stack/CO_PDO.s

# target to generate assembly for a file
CANopenNode/stack/CO_PDO.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_PDO.c.s
.PHONY : CANopenNode/stack/CO_PDO.c.s

CANopenNode/stack/CO_SDO.o: CANopenNode/stack/CO_SDO.c.o

.PHONY : CANopenNode/stack/CO_SDO.o

# target to build an object file
CANopenNode/stack/CO_SDO.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SDO.c.o
.PHONY : CANopenNode/stack/CO_SDO.c.o

CANopenNode/stack/CO_SDO.i: CANopenNode/stack/CO_SDO.c.i

.PHONY : CANopenNode/stack/CO_SDO.i

# target to preprocess a source file
CANopenNode/stack/CO_SDO.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SDO.c.i
.PHONY : CANopenNode/stack/CO_SDO.c.i

CANopenNode/stack/CO_SDO.s: CANopenNode/stack/CO_SDO.c.s

.PHONY : CANopenNode/stack/CO_SDO.s

# target to generate assembly for a file
CANopenNode/stack/CO_SDO.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SDO.c.s
.PHONY : CANopenNode/stack/CO_SDO.c.s

CANopenNode/stack/CO_SDOmaster.o: CANopenNode/stack/CO_SDOmaster.c.o

.PHONY : CANopenNode/stack/CO_SDOmaster.o

# target to build an object file
CANopenNode/stack/CO_SDOmaster.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SDOmaster.c.o
.PHONY : CANopenNode/stack/CO_SDOmaster.c.o

CANopenNode/stack/CO_SDOmaster.i: CANopenNode/stack/CO_SDOmaster.c.i

.PHONY : CANopenNode/stack/CO_SDOmaster.i

# target to preprocess a source file
CANopenNode/stack/CO_SDOmaster.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SDOmaster.c.i
.PHONY : CANopenNode/stack/CO_SDOmaster.c.i

CANopenNode/stack/CO_SDOmaster.s: CANopenNode/stack/CO_SDOmaster.c.s

.PHONY : CANopenNode/stack/CO_SDOmaster.s

# target to generate assembly for a file
CANopenNode/stack/CO_SDOmaster.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SDOmaster.c.s
.PHONY : CANopenNode/stack/CO_SDOmaster.c.s

CANopenNode/stack/CO_SYNC.o: CANopenNode/stack/CO_SYNC.c.o

.PHONY : CANopenNode/stack/CO_SYNC.o

# target to build an object file
CANopenNode/stack/CO_SYNC.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SYNC.c.o
.PHONY : CANopenNode/stack/CO_SYNC.c.o

CANopenNode/stack/CO_SYNC.i: CANopenNode/stack/CO_SYNC.c.i

.PHONY : CANopenNode/stack/CO_SYNC.i

# target to preprocess a source file
CANopenNode/stack/CO_SYNC.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SYNC.c.i
.PHONY : CANopenNode/stack/CO_SYNC.c.i

CANopenNode/stack/CO_SYNC.s: CANopenNode/stack/CO_SYNC.c.s

.PHONY : CANopenNode/stack/CO_SYNC.s

# target to generate assembly for a file
CANopenNode/stack/CO_SYNC.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_SYNC.c.s
.PHONY : CANopenNode/stack/CO_SYNC.c.s

CANopenNode/stack/CO_trace.o: CANopenNode/stack/CO_trace.c.o

.PHONY : CANopenNode/stack/CO_trace.o

# target to build an object file
CANopenNode/stack/CO_trace.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_trace.c.o
.PHONY : CANopenNode/stack/CO_trace.c.o

CANopenNode/stack/CO_trace.i: CANopenNode/stack/CO_trace.c.i

.PHONY : CANopenNode/stack/CO_trace.i

# target to preprocess a source file
CANopenNode/stack/CO_trace.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_trace.c.i
.PHONY : CANopenNode/stack/CO_trace.c.i

CANopenNode/stack/CO_trace.s: CANopenNode/stack/CO_trace.c.s

.PHONY : CANopenNode/stack/CO_trace.s

# target to generate assembly for a file
CANopenNode/stack/CO_trace.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/CO_trace.c.s
.PHONY : CANopenNode/stack/CO_trace.c.s

CANopenNode/stack/crc16-ccitt.o: CANopenNode/stack/crc16-ccitt.c.o

.PHONY : CANopenNode/stack/crc16-ccitt.o

# target to build an object file
CANopenNode/stack/crc16-ccitt.c.o:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/crc16-ccitt.c.o
.PHONY : CANopenNode/stack/crc16-ccitt.c.o

CANopenNode/stack/crc16-ccitt.i: CANopenNode/stack/crc16-ccitt.c.i

.PHONY : CANopenNode/stack/crc16-ccitt.i

# target to preprocess a source file
CANopenNode/stack/crc16-ccitt.c.i:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/crc16-ccitt.c.i
.PHONY : CANopenNode/stack/crc16-ccitt.c.i

CANopenNode/stack/crc16-ccitt.s: CANopenNode/stack/crc16-ccitt.c.s

.PHONY : CANopenNode/stack/crc16-ccitt.s

# target to generate assembly for a file
CANopenNode/stack/crc16-ccitt.c.s:
	$(MAKE) -f CMakeFiles/candaemon.dir/build.make CMakeFiles/candaemon.dir/CANopenNode/stack/crc16-ccitt.c.s
.PHONY : CANopenNode/stack/crc16-ccitt.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... candaemon"
	@echo "... edit_cache"
	@echo "... board"
	@echo "... OD"
	@echo "... common"
	@echo "... driver"
	@echo "... CANopenNode/CANopen.o"
	@echo "... CANopenNode/CANopen.i"
	@echo "... CANopenNode/CANopen.s"
	@echo "... CANopenNode/stack/CO_Emergency.o"
	@echo "... CANopenNode/stack/CO_Emergency.i"
	@echo "... CANopenNode/stack/CO_Emergency.s"
	@echo "... CANopenNode/stack/CO_HBconsumer.o"
	@echo "... CANopenNode/stack/CO_HBconsumer.i"
	@echo "... CANopenNode/stack/CO_HBconsumer.s"
	@echo "... CANopenNode/stack/CO_NMT_Heartbeat.o"
	@echo "... CANopenNode/stack/CO_NMT_Heartbeat.i"
	@echo "... CANopenNode/stack/CO_NMT_Heartbeat.s"
	@echo "... CANopenNode/stack/CO_PDO.o"
	@echo "... CANopenNode/stack/CO_PDO.i"
	@echo "... CANopenNode/stack/CO_PDO.s"
	@echo "... CANopenNode/stack/CO_SDO.o"
	@echo "... CANopenNode/stack/CO_SDO.i"
	@echo "... CANopenNode/stack/CO_SDO.s"
	@echo "... CANopenNode/stack/CO_SDOmaster.o"
	@echo "... CANopenNode/stack/CO_SDOmaster.i"
	@echo "... CANopenNode/stack/CO_SDOmaster.s"
	@echo "... CANopenNode/stack/CO_SYNC.o"
	@echo "... CANopenNode/stack/CO_SYNC.i"
	@echo "... CANopenNode/stack/CO_SYNC.s"
	@echo "... CANopenNode/stack/CO_trace.o"
	@echo "... CANopenNode/stack/CO_trace.i"
	@echo "... CANopenNode/stack/CO_trace.s"
	@echo "... CANopenNode/stack/crc16-ccitt.o"
	@echo "... CANopenNode/stack/crc16-ccitt.i"
	@echo "... CANopenNode/stack/crc16-ccitt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

