#!/bin/sh

# compile python3 code into bytecode
python3 -m compileall /usr/bin/oresat-linux-updater/

# load new daemon service file
systemctl daemon-reload

# make /tmp dir
if [ ! -f "/usr/bin/$PKGNAME" ]; then 
	mkdir /tmp/oresat-linux-updater/
fi

